# Generated by Django 3.0.4 on 2020-03-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='user',
            new_name='users',
        ),
    ]
